name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome, and thank you for contributing! If you are new to Github, please make sure that your issue isn't already addressed."
        pr-message: 'Welcome, and thank you for contributing! If you are new to Rust, please make sure to run `cargo fmt` and `cargo run` to test your code.'
