name: Rust

on:
  push:
    paths:
      - 'src/main.rs'
      - 'src/windows_main.asm'
      - 'src/unix_main.asm'
  pull_request:
    paths:
      - 'src/main.rs'
      - 'src/windows_main.asm'
      - 'src/unix_main.asm'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download dependencies
      run: sudo apt-get install pkg-config libx11-dev libxi-dev libgl1-mesa-dev libasound2-dev
    - name: Download NASM
      run: sudo apt-get install nasm
    - name: Fmt
      run: cargo fmt --check --verbose
    - name: Build
      run: cargo build --verbose
